resources:
  pipelines:
    vendor_mdq_pipeline:
      name: vendor_mdq_pipeline
      catalog: ${var.catalog}
      schema: ${resources.schemas.vendor_mdq.name}
      serverless: true
      channel: CURRENT
      libraries:
        - file:
            path: ./bronze.py
        - file:
            path: ./silver.py
        - file:
            path: ./scd2.py
        - file:
            path: ./gold.py
      configuration:
        inbox: /Volumes/${var.catalog}/${resources.schemas.vendor_mdq.name}/landing/inbox
        initial_load_date: ${var.initial_load_date}
